# The different Materials to look for within the mine structure.
spawnPoint: SPONGE
mineCorner: POWERED_RAIL
sellNpc: WHITE_WOOL
upgradeMaterial: OBSIDIAN
quarryMaterial: SHULKER_BOX
mineDistance: 150
mineYLevel: 50
teleportDelay: 5
addWallGap: true
wallsGap: 1
shouldWallsGoUp: false
giveMineOnFirstJoin: true
preLoginGiveMine: true
onlyReplaceAir: true
borderUpgrade: true
locale: en_US
useAdventure: true
enableMenu: true
enableTax: true
sendTaxMessages: true
defaultClosed: true
resetCooldown: 15
schematicThreads: 4

mineTypes:
  Test:
    file: minewithgap.schem
    resetTime: 5
    expand: 1
    resetPercentage: 15
    upgradeCost: 1.0
    upgradeCurrency: VAULT # Supported currencies: VAULT, ULTRAPRISONCORE (Coming soon, hopefully...)
    useOraxen: false
    useItemsAdder: false
    materials:
      COBBLESTONE: 100.0
    oraxen:
      orax_ore: 0.5
      ruby_ore: 0.5
    itemsAdder:
      nice_stone: 1.0
    flags:
      block-break: true
      upc-enchants: true
    fullFlags:
      block-place: false
    prices:
      COBBLESTONE: 1.0